export const INIT_FEEDS = 'INIT_FEEDS';
export const UPVOTE_NEWSITEM = 'UPVOTE_NEWSITEM';
export const HIDE_NEWS_ITEM = 'HIDE_NEWS_ITEM';
export const ON_LOADMORE_CLICK = 'ON_LOADMORE_CLICK'
export const UPDATE_PAGE= 'UPDATE_PAGE'