export const FETCH_HACKER_NEWS_REQUEST = 'FETCH_HACKER_NEWS_REQUEST';
export const FETCH_HACKER_NEWS_SUCCESS = 'FETCH_HACKER_NEWS_SUCCESS';
export const FETCH_HACKER_NEWS_FAILURE = 'FETCH_HACKER_NEWS_FAILURE';
export const FETCH_HACKER_NEWS_UPDATE = 'FETCH_HACKER_NEWS_UPDATE';
export const UPVOTE_HACKER_NEWS = 'UPVOTE_HACKER_NEWS';
