const FETCH_NEWS_API = 'FETCH_NEWS_API';
const FETCH_NEWS_API_SUCCESS = 'FETCH_NEWS_API_SUCCESS';
const FETCH_NEWS_API_FAILURE = 'FETCH_NEWS_API_FAILURE';
const HIDE_NEWS = 'HIDE_NEWS';
const RECORD_UPVOTE = 'RECORD_UPVOTE';

export {
    FETCH_NEWS_API,
    FETCH_NEWS_API_SUCCESS,
    FETCH_NEWS_API_FAILURE,
    HIDE_NEWS,
    RECORD_UPVOTE
}