export const FETCH_HACKER_NEWS = 'HN/APP/FETCH_HACKER_NEWS';
export const FETCH_HACKER_NEWS_SUCCESS = 'HN/APP/FETCH_HACKER_NEWS_SUCCESS';
export const FETCH_HACKER_NEWS_ERROR = 'HN/APP/FETCH_HACKER_NEWS_ERROR';
